sudo: required

language: generic

services: docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t haeine/react-with-docker -f Dockerfile.dev .

script:
    - docker run -d CI=true haeine/react-with-docker num run test --coverage

after_success:
    - echo "Test Success"
