version: "3"
services:
    react:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /code/node_modules
            - ./:/code
        stdin_open: true
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /code/node_modules
            - ./:/code
        command: ["npm", "run", "test"]
